"""Tests added by adversarial-review round 4 (delivery): pins two
behaviors that exist in deliver.py but were untested — the spec §1.4 15%
rrd-sampling floor override (review-r4 #10) and cross-midnight
staged-date pinning on a PACKAGED resume (review-r4 #11)."""
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from pipeline import config as C
from pipeline import deliver

SID = "2026-08-15T10-00-00Z_kamla_c_00000000000000a1"
SID_RESUME = "2026-08-14T23-50-00Z_kamla_c_00000000000000c2"


def _seed_ready(cfg, ledger, sid=SID, game="kamla"):
    """A READY session with the 3 spec files in work/ — enough for the
    real stage_session. Unlike test_deliver._fake_session, adds NO filler
    delivery: the floor tests control today's delivered set themselves."""
    ledger.insert_session(
        session_id=sid, game=game, operator_email="Op",
        player_email="p@x.com", drive_path=f"{game}/Op/p/{sid}",
        drive_ctime="2026-08-15T10:00:00.000Z", md5_video="m", bytes_=1,
        state="READY")
    work = cfg.work / sid
    work.mkdir(parents=True, exist_ok=True)
    (work / "video.mp4").write_bytes(b"vv")
    (work / "frames.csv").write_text("frame_id\n0\n")
    (work / "session.json").write_text(json.dumps(
        {"session_id": sid, "duration_seconds": 90.0}))
    return work


def _seed_delivered_today(ledger, sid, game="kamla", sampled=0):
    """A DELIVERED row whose delivered_at starts with today's UTC
    %Y-%m-%d — the exact prefix the §1.4 floor query LIKE-filters on."""
    ledger.insert_session(
        session_id=sid, game=game, operator_email="Op",
        player_email="p@x.com", drive_path=f"{game}/Op/p/{sid}",
        drive_ctime="2026-08-15T00:00:00.000Z", md5_video=f"m-{sid[-2:]}",
        bytes_=1, state="DELIVERED")
    ledger.update(sid, rrd_sampled=sampled, duration_delivered_s=100.0,
                  delivered_at=datetime.now(timezone.utc).isoformat(
                      timespec="seconds"))


def _fake_rclone(uploaded):
    """test_deliver.py's capture pattern, extended to record EVERY copy
    destination and every lsjson verification target."""
    def fake(args, **kw):
        if args[0] == "copy":
            src = Path(args[-2])
            uploaded["files"] = {
                f.name: {"Size": f.stat().st_size,
                         "Hashes": {"md5": hashlib.md5(
                             f.read_bytes()).hexdigest()}}
                for f in src.iterdir() if f.is_file()}
            uploaded.setdefault("copy_dests", []).append(args[-1])
            return subprocess.CompletedProcess(args, 0, "", "")
        if args[0] == "lsjson":
            uploaded.setdefault("lsjson_dests", []).append(args[-1])
            out = [dict(Name=n, IsDir=False, **v)
                   for n, v in uploaded.get("files", {}).items()]
            return subprocess.CompletedProcess(args, 0, json.dumps(out), "")
        return subprocess.CompletedProcess(args, 0, "[]", "")
    return fake


def _patch_boundaries(monkeypatch, regen, gate_sampled, uploaded,
                      draw=False):
    """Monkeypatch ONLY the I/O boundaries: the deterministic draw, the
    rrd pair generation, the qa-v2 gate (needs real media), and rclone.
    The floor arithmetic and staged-date resolution run for real."""
    monkeypatch.setattr(deliver, "rrd_sampled", lambda *a, **k: draw)
    monkeypatch.setattr(deliver.rrdmod, "write_script",
                        lambda d: regen.append("script"))
    monkeypatch.setattr(deliver.rrdmod, "generate",
                        lambda d, **kw: regen.append("rrd"))

    def gate(stage_dir, sampled):
        gate_sampled.append(sampled)
        return True, []
    monkeypatch.setattr(deliver, "final_gate", gate)
    monkeypatch.setattr(deliver, "run_rclone", _fake_rclone(uploaded))


# ------------------------------------------------ §1.4 15% floor (r4 #10)

def test_floor_forces_sampling_when_under_15pct(cfg, ledger, monkeypatch):
    """review-r4 #10 — 2 unsampled deliveries today + this one = 3, so
    need ceil(15% * 3) = 1 sampled > 0: the False deterministic draw is
    OVERRIDDEN — rrd pair regenerated, final gate sees sampled=True, and
    the ledger row ends rrd_sampled=1."""
    _seed_ready(cfg, ledger)
    _seed_delivered_today(
        ledger, "2026-08-15T01-00-00Z_kamla_c_00000000000000b1", sampled=0)
    _seed_delivered_today(
        ledger, "2026-08-15T02-00-00Z_kamla_c_00000000000000b2", sampled=0)
    regen, gate_sampled, uploaded = [], [], {}
    _patch_boundaries(monkeypatch, regen, gate_sampled, uploaded,
                      draw=False)
    out = deliver.deliver_session(cfg, ledger, SID)
    assert out.status == "delivered"
    assert out.rrd_sampled is True
    assert regen == ["script", "rrd"]        # pair regenerated by the floor
    assert gate_sampled == [True]            # gate saw the override
    assert ledger.get(SID)["rrd_sampled"] == 1


def test_floor_met_leaves_false_draw_unsampled(cfg, ledger, monkeypatch):
    """review-r4 #10 inverse — floor already met (2/2 sampled today, need
    is 1): the False draw stands — NO rrd regeneration, gate sees
    sampled=False, ledger row stays rrd_sampled=0."""
    _seed_ready(cfg, ledger)
    _seed_delivered_today(
        ledger, "2026-08-15T01-00-00Z_kamla_c_00000000000000b1", sampled=1)
    _seed_delivered_today(
        ledger, "2026-08-15T02-00-00Z_kamla_c_00000000000000b2", sampled=1)
    regen, gate_sampled, uploaded = [], [], {}
    _patch_boundaries(monkeypatch, regen, gate_sampled, uploaded,
                      draw=False)
    out = deliver.deliver_session(cfg, ledger, SID)
    assert out.status == "delivered"
    assert out.rrd_sampled is False
    assert regen == []                       # floor satisfied: no override
    assert gate_sampled == [False]
    assert ledger.get(SID)["rrd_sampled"] == 0


# ------------------------------- cross-midnight staged_date pin (r4 #11)

def test_resume_uploads_under_staged_date_not_today(cfg, ledger,
                                                    monkeypatch):
    """review-r4 #11 — a PACKAGED resume must finish under the SAME dated
    remote path as the original staging; re-dating to today would
    double-deliver the session under two paths after a cross-midnight
    crash. Also re-checks the stale half-staged files never ship (the
    resume re-stages fresh from work/)."""
    _seed_ready(cfg, ledger, sid=SID_RESUME)
    ledger.set_state(SID_RESUME, "PACKAGED",
                     "staged 08-14-2026 rrd_sampled=False")
    ledger.update(SID_RESUME, rrd_sampled=0)
    # the crashed run's staged copy from yesterday — its EXISTENCE pins
    # the date; its 5 stale files get wiped by the fresh re-stage
    staged = cfg.stage / C.VENDOR / "08-14-2026" / "kamla" / SID_RESUME
    staged.mkdir(parents=True)
    for name in (*deliver.SPEC_FILES, *deliver.RRD_FILES):
        (staged / name).write_bytes(b"stale")
    regen, gate_sampled, uploaded = [], [], {}
    _patch_boundaries(monkeypatch, regen, gate_sampled, uploaded,
                      draw=False)
    out = deliver.deliver_session(cfg, ledger, SID_RESUME)
    assert out.status == "delivered"
    # exactly one remote session dir written, under the STAGED date
    pinned = (f"{cfg.remote_deliver}{C.VENDOR}/08-14-2026/kamla/"
              f"{SID_RESUME}")
    assert uploaded["copy_dests"] == [pinned]
    assert uploaded["lsjson_dests"] == [pinned]   # verified there too
    today = deliver.upload_date_utc()
    if today != "08-14-2026":                     # never true in CI today
        assert all(today not in d for d in uploaded["copy_dests"])
    # no second dated dir appeared in the local staging tree either
    assert [d.name for d in (cfg.stage / C.VENDOR).iterdir()] \
        == ["08-14-2026"]
    # fresh re-stage: the 3 spec files shipped, the stale rrd pair didn't
    assert set(uploaded["files"]) == set(deliver.SPEC_FILES)
    assert regen == []                       # recorded rrd_sampled=0 honored
    assert ledger.get(SID_RESUME)["state"] == "DELIVERED"
